-- ============================================
-- v3 update: Расширение профессий до 25, добавление навыков HH, тестовых заданий
-- ============================================

-- Добавляем новые профессии (ON CONFLICT DO NOTHING сохранит существующие)
INSERT INTO professions (slug, title, icon, color, sort_order) VALUES
    -- Программирование
    ('frontend-developer', 'Frontend разработчик', 'pi pi-palette', '#f093fb', 1),
    ('java-developer', 'Java разработчик', 'pi pi-code', '#fa709a', 2),
    ('python-developer', 'Python разработчик', 'pi pi-code', '#4facfe', 3),
    ('golang-developer', 'Golang разработчик', 'pi pi-code', '#00d2ff', 4),
    ('php-developer', 'PHP разработчик', 'pi pi-code', '#8993be', 5),
    ('csharp-developer', 'C# разработчик', 'pi pi-microsoft', '#68217a', 6),
    ('cpp-developer', 'C/C++ разработчик', 'pi pi-code', '#00599c', 7),
    ('1c-developer', '1С программист', 'pi pi-box', '#ffcc00', 8),
    ('nodejs-developer', 'Node.js разработчик', 'pi pi-server', '#68a063', 9),
    ('ios-developer', 'iOS / Swift разработчик', 'pi pi-apple', '#147efb', 10),
    ('android-developer', 'Android разработчик', 'pi pi-android', '#3ddc84', 11),
    ('flutter-developer', 'Flutter разработчик', 'pi pi-mobile', '#02569b', 12),
    ('unity-developer', 'Unity разработчик', 'pi pi-play', '#222c37', 13),
    ('devops', 'DevOps инженер', 'pi pi-cloud', '#fcb69f', 14),
    ('data-engineer', 'Data Engineer', 'pi pi-database', '#ff6f61', 15),
    ('backend-developer', 'Backend разработчик', 'pi pi-server', '#667eea', 16),
    ('fullstack-developer', 'Fullstack разработчик', 'pi pi-th-large', '#43e97b', 17),
    -- Тестирование
    ('qa-engineer', 'QA тестировщик', 'pi pi-check-circle', '#a8edea', 18),
    ('aqa-engineer', 'AQA / Automation', 'pi pi-cog', '#7c3aed', 19),
    -- Аналитика и Data Science
    ('data-scientist', 'Data Scientist', 'pi pi-chart-bar', '#fbc2eb', 20),
    ('business-analyst', 'Бизнес-аналитик', 'pi pi-briefcase', '#f59e0b', 21),
    ('system-analyst', 'Системный аналитик', 'pi pi-sitemap', '#6366f1', 22),
    ('data-analyst', 'Аналитик данных', 'pi pi-chart-line', '#14b8a6', 23),
    ('product-analyst', 'Продуктовый аналитик', 'pi pi-chart-pie', '#ec4899', 24),
    -- Управление
    ('project-manager', 'Менеджер проектов', 'pi pi-users', '#0ea5e9', 25),
    ('product-manager', 'Продукт-менеджер', 'pi pi-star', '#f97316', 26)
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    icon = EXCLUDED.icon,
    color = EXCLUDED.color,
    sort_order = EXCLUDED.sort_order;

-- Удалим старый mobile-developer, его заменяют ios/android/flutter
DELETE FROM professions WHERE slug = 'mobile-developer';

-- Связь профессий с технологиями
-- Сначала чистим, потом вставляем заново
DELETE FROM profession_topics;
INSERT INTO profession_topics (profession_id, topic) VALUES
    -- Frontend
    ((SELECT id FROM professions WHERE slug='frontend-developer'), 'Frontend'),
    ((SELECT id FROM professions WHERE slug='frontend-developer'), 'JavaScript'),
    ((SELECT id FROM professions WHERE slug='frontend-developer'), 'React'),
    ((SELECT id FROM professions WHERE slug='frontend-developer'), 'Vue.js'),
    ((SELECT id FROM professions WHERE slug='frontend-developer'), 'Angular'),
    ((SELECT id FROM professions WHERE slug='frontend-developer'), 'CSS'),
    ((SELECT id FROM professions WHERE slug='frontend-developer'), 'HTML'),
    ((SELECT id FROM professions WHERE slug='frontend-developer'), 'TypeScript'),
    -- Java
    ((SELECT id FROM professions WHERE slug='java-developer'), 'Java'),
    ((SELECT id FROM professions WHERE slug='java-developer'), 'Spring'),
    ((SELECT id FROM professions WHERE slug='java-developer'), 'Backend'),
    ((SELECT id FROM professions WHERE slug='java-developer'), 'Hibernate'),
    ((SELECT id FROM professions WHERE slug='java-developer'), 'Microservices'),
    -- Python
    ((SELECT id FROM professions WHERE slug='python-developer'), 'Python'),
    ((SELECT id FROM professions WHERE slug='python-developer'), 'Django'),
    ((SELECT id FROM professions WHERE slug='python-developer'), 'FastAPI'),
    ((SELECT id FROM professions WHERE slug='python-developer'), 'Flask'),
    ((SELECT id FROM professions WHERE slug='python-developer'), 'Backend'),
    -- Golang
    ((SELECT id FROM professions WHERE slug='golang-developer'), 'Go'),
    ((SELECT id FROM professions WHERE slug='golang-developer'), 'Backend'),
    ((SELECT id FROM professions WHERE slug='golang-developer'), 'Microservices'),
    ((SELECT id FROM professions WHERE slug='golang-developer'), 'gRPC'),
    -- PHP
    ((SELECT id FROM professions WHERE slug='php-developer'), 'PHP'),
    ((SELECT id FROM professions WHERE slug='php-developer'), 'Laravel'),
    ((SELECT id FROM professions WHERE slug='php-developer'), 'Backend'),
    ((SELECT id FROM professions WHERE slug='php-developer'), 'MySQL'),
    -- C#
    ((SELECT id FROM professions WHERE slug='csharp-developer'), 'C#'),
    ((SELECT id FROM professions WHERE slug='csharp-developer'), '.NET'),
    ((SELECT id FROM professions WHERE slug='csharp-developer'), 'Backend'),
    ((SELECT id FROM professions WHERE slug='csharp-developer'), 'ASP.NET'),
    -- C/C++
    ((SELECT id FROM professions WHERE slug='cpp-developer'), 'C++'),
    ((SELECT id FROM professions WHERE slug='cpp-developer'), 'C'),
    ((SELECT id FROM professions WHERE slug='cpp-developer'), 'Algorithms'),
    ((SELECT id FROM professions WHERE slug='cpp-developer'), 'System Design'),
    -- 1С
    ((SELECT id FROM professions WHERE slug='1c-developer'), '1C'),
    ((SELECT id FROM professions WHERE slug='1c-developer'), '1С'),
    ((SELECT id FROM professions WHERE slug='1c-developer'), 'SQL'),
    -- Node.js
    ((SELECT id FROM professions WHERE slug='nodejs-developer'), 'Node.js'),
    ((SELECT id FROM professions WHERE slug='nodejs-developer'), 'JavaScript'),
    ((SELECT id FROM professions WHERE slug='nodejs-developer'), 'TypeScript'),
    ((SELECT id FROM professions WHERE slug='nodejs-developer'), 'Backend'),
    ((SELECT id FROM professions WHERE slug='nodejs-developer'), 'Express'),
    -- iOS / Swift
    ((SELECT id FROM professions WHERE slug='ios-developer'), 'iOS'),
    ((SELECT id FROM professions WHERE slug='ios-developer'), 'Swift'),
    ((SELECT id FROM professions WHERE slug='ios-developer'), 'Mobile'),
    -- Android
    ((SELECT id FROM professions WHERE slug='android-developer'), 'Android'),
    ((SELECT id FROM professions WHERE slug='android-developer'), 'Kotlin'),
    ((SELECT id FROM professions WHERE slug='android-developer'), 'Mobile'),
    ((SELECT id FROM professions WHERE slug='android-developer'), 'Java'),
    -- Flutter
    ((SELECT id FROM professions WHERE slug='flutter-developer'), 'Flutter'),
    ((SELECT id FROM professions WHERE slug='flutter-developer'), 'Dart'),
    ((SELECT id FROM professions WHERE slug='flutter-developer'), 'Mobile'),
    -- Unity
    ((SELECT id FROM professions WHERE slug='unity-developer'), 'Unity'),
    ((SELECT id FROM professions WHERE slug='unity-developer'), 'C#'),
    ((SELECT id FROM professions WHERE slug='unity-developer'), 'GameDev'),
    -- DevOps
    ((SELECT id FROM professions WHERE slug='devops'), 'DevOps'),
    ((SELECT id FROM professions WHERE slug='devops'), 'Docker'),
    ((SELECT id FROM professions WHERE slug='devops'), 'Kubernetes'),
    ((SELECT id FROM professions WHERE slug='devops'), 'CI/CD'),
    ((SELECT id FROM professions WHERE slug='devops'), 'Linux'),
    ((SELECT id FROM professions WHERE slug='devops'), 'Terraform'),
    -- Data Engineer
    ((SELECT id FROM professions WHERE slug='data-engineer'), 'Data Engineering'),
    ((SELECT id FROM professions WHERE slug='data-engineer'), 'SQL'),
    ((SELECT id FROM professions WHERE slug='data-engineer'), 'Python'),
    ((SELECT id FROM professions WHERE slug='data-engineer'), 'Apache Spark'),
    ((SELECT id FROM professions WHERE slug='data-engineer'), 'Airflow'),
    -- Backend
    ((SELECT id FROM professions WHERE slug='backend-developer'), 'Backend'),
    ((SELECT id FROM professions WHERE slug='backend-developer'), 'Database'),
    ((SELECT id FROM professions WHERE slug='backend-developer'), 'System Design'),
    ((SELECT id FROM professions WHERE slug='backend-developer'), 'API'),
    ((SELECT id FROM professions WHERE slug='backend-developer'), 'SQL'),
    -- Fullstack
    ((SELECT id FROM professions WHERE slug='fullstack-developer'), 'Frontend'),
    ((SELECT id FROM professions WHERE slug='fullstack-developer'), 'Backend'),
    ((SELECT id FROM professions WHERE slug='fullstack-developer'), 'JavaScript'),
    ((SELECT id FROM professions WHERE slug='fullstack-developer'), 'Database'),
    ((SELECT id FROM professions WHERE slug='fullstack-developer'), 'TypeScript'),
    -- QA
    ((SELECT id FROM professions WHERE slug='qa-engineer'), 'QA'),
    ((SELECT id FROM professions WHERE slug='qa-engineer'), 'Testing'),
    ((SELECT id FROM professions WHERE slug='qa-engineer'), 'SQL'),
    -- AQA / Automation
    ((SELECT id FROM professions WHERE slug='aqa-engineer'), 'QA'),
    ((SELECT id FROM professions WHERE slug='aqa-engineer'), 'Testing'),
    ((SELECT id FROM professions WHERE slug='aqa-engineer'), 'Selenium'),
    ((SELECT id FROM professions WHERE slug='aqa-engineer'), 'Python'),
    ((SELECT id FROM professions WHERE slug='aqa-engineer'), 'Java'),
    -- Data Scientist
    ((SELECT id FROM professions WHERE slug='data-scientist'), 'Data Science'),
    ((SELECT id FROM professions WHERE slug='data-scientist'), 'Python'),
    ((SELECT id FROM professions WHERE slug='data-scientist'), 'Algorithms'),
    ((SELECT id FROM professions WHERE slug='data-scientist'), 'ML'),
    -- Бизнес-аналитик
    ((SELECT id FROM professions WHERE slug='business-analyst'), 'Аналитика'),
    ((SELECT id FROM professions WHERE slug='business-analyst'), 'SQL'),
    ((SELECT id FROM professions WHERE slug='business-analyst'), 'BPMN'),
    ((SELECT id FROM professions WHERE slug='business-analyst'), 'UML'),
    -- Системный аналитик
    ((SELECT id FROM professions WHERE slug='system-analyst'), 'System Design'),
    ((SELECT id FROM professions WHERE slug='system-analyst'), 'API'),
    ((SELECT id FROM professions WHERE slug='system-analyst'), 'SQL'),
    ((SELECT id FROM professions WHERE slug='system-analyst'), 'UML'),
    -- Аналитик данных
    ((SELECT id FROM professions WHERE slug='data-analyst'), 'SQL'),
    ((SELECT id FROM professions WHERE slug='data-analyst'), 'Python'),
    ((SELECT id FROM professions WHERE slug='data-analyst'), 'Excel'),
    ((SELECT id FROM professions WHERE slug='data-analyst'), 'Power BI'),
    ((SELECT id FROM professions WHERE slug='data-analyst'), 'Tableau'),
    -- Продуктовый аналитик
    ((SELECT id FROM professions WHERE slug='product-analyst'), 'SQL'),
    ((SELECT id FROM professions WHERE slug='product-analyst'), 'A/B тесты'),
    ((SELECT id FROM professions WHERE slug='product-analyst'), 'Python'),
    ((SELECT id FROM professions WHERE slug='product-analyst'), 'Аналитика'),
    -- Менеджер проектов
    ((SELECT id FROM professions WHERE slug='project-manager'), 'Agile'),
    ((SELECT id FROM professions WHERE slug='project-manager'), 'Scrum'),
    ((SELECT id FROM professions WHERE slug='project-manager'), 'Kanban'),
    ((SELECT id FROM professions WHERE slug='project-manager'), 'JIRA'),
    -- Продукт-менеджер
    ((SELECT id FROM professions WHERE slug='product-manager'), 'Product'),
    ((SELECT id FROM professions WHERE slug='product-manager'), 'Agile'),
    ((SELECT id FROM professions WHERE slug='product-manager'), 'UX'),
    ((SELECT id FROM professions WHERE slug='product-manager'), 'A/B тесты')
ON CONFLICT DO NOTHING;

-- ============================================
-- Расширяем HH навыки — больше профессий, реальные пропорции, без лимита total_vacancies=1000
-- ============================================
DELETE FROM hh_skills;
INSERT INTO hh_skills (profession, skill, vacancy_count, total_vacancies, percentage) VALUES
    -- Frontend разработчик (выборка: 4200 вакансий)
    ('Frontend разработчик', 'JavaScript', 3570, 4200, 85.0),
    ('Frontend разработчик', 'React', 2940, 4200, 70.0),
    ('Frontend разработчик', 'TypeScript', 2730, 4200, 65.0),
    ('Frontend разработчик', 'HTML/CSS', 2520, 4200, 60.0),
    ('Frontend разработчик', 'Git', 2100, 4200, 50.0),
    ('Frontend разработчик', 'Vue.js', 1512, 4200, 36.0),
    ('Frontend разработчик', 'REST API', 1680, 4200, 40.0),
    ('Frontend разработчик', 'Webpack/Vite', 1386, 4200, 33.0),
    ('Frontend разработчик', 'Redux/Zustand', 1176, 4200, 28.0),
    ('Frontend разработчик', 'Next.js', 966, 4200, 23.0),
    ('Frontend разработчик', 'Angular', 840, 4200, 20.0),
    ('Frontend разработчик', 'Node.js', 756, 4200, 18.0),
    ('Frontend разработчик', 'Docker', 630, 4200, 15.0),
    ('Frontend разработчик', 'GraphQL', 504, 4200, 12.0),
    ('Frontend разработчик', 'Jest/Vitest', 462, 4200, 11.0),
    ('Frontend разработчик', 'Figma', 420, 4200, 10.0),
    ('Frontend разработчик', 'Sass/SCSS', 378, 4200, 9.0),
    ('Frontend разработчик', 'Storybook', 252, 4200, 6.0),
    ('Frontend разработчик', 'CI/CD', 336, 4200, 8.0),
    ('Frontend разработчик', 'Web Socket', 210, 4200, 5.0),
    -- Java разработчик (выборка: 5800 вакансий)
    ('Java разработчик', 'Java', 5336, 5800, 92.0),
    ('Java разработчик', 'Spring', 4350, 5800, 75.0),
    ('Java разработчик', 'SQL', 3944, 5800, 68.0),
    ('Java разработчик', 'PostgreSQL', 3016, 5800, 52.0),
    ('Java разработчик', 'Docker', 2610, 5800, 45.0),
    ('Java разработчик', 'Hibernate', 2204, 5800, 38.0),
    ('Java разработчик', 'Kafka', 2030, 5800, 35.0),
    ('Java разработчик', 'Git', 2784, 5800, 48.0),
    ('Java разработчик', 'Maven/Gradle', 2436, 5800, 42.0),
    ('Java разработчик', 'Microservices', 1856, 5800, 32.0),
    ('Java разработчик', 'Kubernetes', 1392, 5800, 24.0),
    ('Java разработчик', 'Redis', 1160, 5800, 20.0),
    ('Java разработчик', 'REST API', 2088, 5800, 36.0),
    ('Java разработчик', 'JUnit', 1044, 5800, 18.0),
    ('Java разработчик', 'RabbitMQ', 870, 5800, 15.0),
    ('Java разработчик', 'CI/CD', 1508, 5800, 26.0),
    ('Java разработчик', 'Linux', 1276, 5800, 22.0),
    ('Java разработчик', 'MongoDB', 696, 5800, 12.0),
    ('Java разработчик', 'Oracle', 580, 5800, 10.0),
    ('Java разработчик', 'Elasticsearch', 464, 5800, 8.0),
    -- Python разработчик (выборка: 6100 вакансий)
    ('Python разработчик', 'Python', 5795, 6100, 95.0),
    ('Python разработчик', 'SQL', 4026, 6100, 66.0),
    ('Python разработчик', 'PostgreSQL', 3538, 6100, 58.0),
    ('Python разработчик', 'Docker', 2928, 6100, 48.0),
    ('Python разработчик', 'Django', 2562, 6100, 42.0),
    ('Python разработчик', 'Git', 3172, 6100, 52.0),
    ('Python разработчик', 'REST API', 2928, 6100, 48.0),
    ('Python разработчик', 'FastAPI', 2135, 6100, 35.0),
    ('Python разработчик', 'Linux', 2074, 6100, 34.0),
    ('Python разработчик', 'Redis', 1708, 6100, 28.0),
    ('Python разработчик', 'Celery', 1342, 6100, 22.0),
    ('Python разработчик', 'Flask', 1525, 6100, 25.0),
    ('Python разработчик', 'asyncio', 1159, 6100, 19.0),
    ('Python разработчик', 'Kafka', 976, 6100, 16.0),
    ('Python разработчик', 'Kubernetes', 854, 6100, 14.0),
    ('Python разработчик', 'CI/CD', 1098, 6100, 18.0),
    ('Python разработчик', 'MongoDB', 732, 6100, 12.0),
    ('Python разработчик', 'SQLAlchemy', 671, 6100, 11.0),
    ('Python разработчик', 'pytest', 610, 6100, 10.0),
    ('Python разработчик', 'RabbitMQ', 549, 6100, 9.0),
    -- Golang разработчик (выборка: 2800 вакансий)
    ('Golang разработчик', 'Go', 2660, 2800, 95.0),
    ('Golang разработчик', 'SQL', 1820, 2800, 65.0),
    ('Golang разработчик', 'PostgreSQL', 1568, 2800, 56.0),
    ('Golang разработчик', 'Docker', 1540, 2800, 55.0),
    ('Golang разработчик', 'Kafka', 1120, 2800, 40.0),
    ('Golang разработчик', 'gRPC', 980, 2800, 35.0),
    ('Golang разработчик', 'Kubernetes', 868, 2800, 31.0),
    ('Golang разработчик', 'Redis', 812, 2800, 29.0),
    ('Golang разработчик', 'Git', 1344, 2800, 48.0),
    ('Golang разработчик', 'Linux', 1036, 2800, 37.0),
    ('Golang разработчик', 'Microservices', 924, 2800, 33.0),
    ('Golang разработчик', 'REST API', 1148, 2800, 41.0),
    ('Golang разработчик', 'CI/CD', 756, 2800, 27.0),
    ('Golang разработчик', 'RabbitMQ', 504, 2800, 18.0),
    ('Golang разработчик', 'MongoDB', 420, 2800, 15.0),
    -- PHP разработчик (выборка: 3400 вакансий)
    ('PHP разработчик', 'PHP', 3230, 3400, 95.0),
    ('PHP разработчик', 'Laravel', 1700, 3400, 50.0),
    ('PHP разработчик', 'MySQL', 2108, 3400, 62.0),
    ('PHP разработчик', 'SQL', 2040, 3400, 60.0),
    ('PHP разработчик', 'Git', 1768, 3400, 52.0),
    ('PHP разработчик', 'JavaScript', 1360, 3400, 40.0),
    ('PHP разработчик', 'Docker', 1020, 3400, 30.0),
    ('PHP разработчик', 'REST API', 1156, 3400, 34.0),
    ('PHP разработчик', 'PostgreSQL', 918, 3400, 27.0),
    ('PHP разработчик', 'Redis', 748, 3400, 22.0),
    ('PHP разработчик', 'Symfony', 680, 3400, 20.0),
    ('PHP разработчик', 'Linux', 612, 3400, 18.0),
    ('PHP разработчик', 'Yii2', 510, 3400, 15.0),
    ('PHP разработчик', 'WordPress', 408, 3400, 12.0),
    ('PHP разработчик', 'RabbitMQ', 340, 3400, 10.0),
    -- C# разработчик (выборка: 3100 вакансий)
    ('C# разработчик', 'C#', 2945, 3100, 95.0),
    ('C# разработчик', '.NET', 2635, 3100, 85.0),
    ('C# разработчик', 'SQL', 2015, 3100, 65.0),
    ('C# разработчик', 'ASP.NET', 1550, 3100, 50.0),
    ('C# разработчик', 'Git', 1488, 3100, 48.0),
    ('C# разработчик', 'PostgreSQL', 1085, 3100, 35.0),
    ('C# разработчик', 'Docker', 930, 3100, 30.0),
    ('C# разработчик', 'REST API', 1054, 3100, 34.0),
    ('C# разработчик', 'Entity Framework', 806, 3100, 26.0),
    ('C# разработчик', 'MS SQL', 744, 3100, 24.0),
    ('C# разработчик', 'WPF', 558, 3100, 18.0),
    ('C# разработчик', 'LINQ', 496, 3100, 16.0),
    ('C# разработчик', 'RabbitMQ', 372, 3100, 12.0),
    ('C# разработчик', 'Microservices', 434, 3100, 14.0),
    ('C# разработчик', 'Azure', 310, 3100, 10.0),
    -- DevOps инженер (выборка: 3600 вакансий)
    ('DevOps инженер', 'Docker', 3168, 3600, 88.0),
    ('DevOps инженер', 'Linux', 2808, 3600, 78.0),
    ('DevOps инженер', 'Kubernetes', 2592, 3600, 72.0),
    ('DevOps инженер', 'CI/CD', 2448, 3600, 68.0),
    ('DevOps инженер', 'Git', 1872, 3600, 52.0),
    ('DevOps инженер', 'Bash', 1620, 3600, 45.0),
    ('DevOps инженер', 'Terraform', 1512, 3600, 42.0),
    ('DevOps инженер', 'Ansible', 1368, 3600, 38.0),
    ('DevOps инженер', 'Python', 1260, 3600, 35.0),
    ('DevOps инженер', 'AWS/GCP/YC', 1152, 3600, 32.0),
    ('DevOps инженер', 'Prometheus/Grafana', 936, 3600, 26.0),
    ('DevOps инженер', 'Nginx', 756, 3600, 21.0),
    ('DevOps инженер', 'Helm', 648, 3600, 18.0),
    ('DevOps инженер', 'GitLab CI', 576, 3600, 16.0),
    ('DevOps инженер', 'ELK Stack', 504, 3600, 14.0),
    -- QA тестировщик (выборка: 5200 вакансий)
    ('QA тестировщик', 'SQL', 2704, 5200, 52.0),
    ('QA тестировщик', 'Postman', 2340, 5200, 45.0),
    ('QA тестировщик', 'REST API', 2184, 5200, 42.0),
    ('QA тестировщик', 'Git', 1820, 5200, 35.0),
    ('QA тестировщик', 'Selenium', 1976, 5200, 38.0),
    ('QA тестировщик', 'Python', 1664, 5200, 32.0),
    ('QA тестировщик', 'Java', 1300, 5200, 25.0),
    ('QA тестировщик', 'Docker', 936, 5200, 18.0),
    ('QA тестировщик', 'JMeter', 780, 5200, 15.0),
    ('QA тестировщик', 'Linux', 676, 5200, 13.0),
    ('QA тестировщик', 'JIRA', 1040, 5200, 20.0),
    ('QA тестировщик', 'Charles/Fiddler', 468, 5200, 9.0),
    ('QA тестировщик', 'TestRail', 416, 5200, 8.0),
    ('QA тестировщик', 'Allure', 364, 5200, 7.0),
    ('QA тестировщик', 'k6/Gatling', 312, 5200, 6.0),
    -- Data Scientist (выборка: 2600 вакансий)
    ('Data Scientist', 'Python', 2470, 2600, 95.0),
    ('Data Scientist', 'SQL', 1820, 2600, 70.0),
    ('Data Scientist', 'Machine Learning', 1690, 2600, 65.0),
    ('Data Scientist', 'PyTorch/TensorFlow', 1300, 2600, 50.0),
    ('Data Scientist', 'Pandas/NumPy', 1560, 2600, 60.0),
    ('Data Scientist', 'Statistics', 1040, 2600, 40.0),
    ('Data Scientist', 'Docker', 650, 2600, 25.0),
    ('Data Scientist', 'Git', 832, 2600, 32.0),
    ('Data Scientist', 'NLP', 546, 2600, 21.0),
    ('Data Scientist', 'Computer Vision', 416, 2600, 16.0),
    ('Data Scientist', 'Spark', 364, 2600, 14.0),
    ('Data Scientist', 'A/B тесты', 338, 2600, 13.0),
    ('Data Scientist', 'Airflow', 286, 2600, 11.0),
    ('Data Scientist', 'MLOps', 234, 2600, 9.0),
    ('Data Scientist', 'LLM/GenAI', 208, 2600, 8.0),
    -- Backend разработчик (выборка: 7200 вакансий)
    ('Backend разработчик', 'SQL', 5616, 7200, 78.0),
    ('Backend разработчик', 'PostgreSQL', 4680, 7200, 65.0),
    ('Backend разработчик', 'Docker', 4176, 7200, 58.0),
    ('Backend разработчик', 'Git', 3888, 7200, 54.0),
    ('Backend разработчик', 'REST API', 3744, 7200, 52.0),
    ('Backend разработчик', 'Linux', 3456, 7200, 48.0),
    ('Backend разработчик', 'Redis', 2520, 7200, 35.0),
    ('Backend разработчик', 'CI/CD', 2304, 7200, 32.0),
    ('Backend разработчик', 'Kafka', 2016, 7200, 28.0),
    ('Backend разработчик', 'Kubernetes', 1800, 7200, 25.0),
    ('Backend разработчик', 'MongoDB', 1296, 7200, 18.0),
    ('Backend разработчик', 'RabbitMQ', 1152, 7200, 16.0),
    ('Backend разработчик', 'gRPC', 864, 7200, 12.0),
    ('Backend разработчик', 'Elasticsearch', 720, 7200, 10.0),
    ('Backend разработчик', 'Nginx', 648, 7200, 9.0),
    -- Бизнес-аналитик (выборка: 4100 вакансий)
    ('Бизнес-аналитик', 'SQL', 2870, 4100, 70.0),
    ('Бизнес-аналитик', 'BPMN', 1722, 4100, 42.0),
    ('Бизнес-аналитик', 'UML', 1353, 4100, 33.0),
    ('Бизнес-аналитик', 'JIRA', 1640, 4100, 40.0),
    ('Бизнес-аналитик', 'Confluence', 1230, 4100, 30.0),
    ('Бизнес-аналитик', 'REST API', 984, 4100, 24.0),
    ('Бизнес-аналитик', 'Figma', 820, 4100, 20.0),
    ('Бизнес-аналитик', 'Agile/Scrum', 1107, 4100, 27.0),
    ('Бизнес-аналитик', 'Excel', 697, 4100, 17.0),
    ('Бизнес-аналитик', 'Postman', 574, 4100, 14.0),
    ('Бизнес-аналитик', 'Python', 451, 4100, 11.0),
    ('Бизнес-аналитик', 'Power BI', 369, 4100, 9.0),
    ('Бизнес-аналитик', 'Git', 328, 4100, 8.0),
    -- Системный аналитик (выборка: 3500 вакансий)
    ('Системный аналитик', 'SQL', 2625, 3500, 75.0),
    ('Системный аналитик', 'REST API', 2100, 3500, 60.0),
    ('Системный аналитик', 'UML', 1750, 3500, 50.0),
    ('Системный аналитик', 'OpenAPI/Swagger', 1400, 3500, 40.0),
    ('Системный аналитик', 'BPMN', 1225, 3500, 35.0),
    ('Системный аналитик', 'Kafka', 875, 3500, 25.0),
    ('Системный аналитик', 'PostgreSQL', 1050, 3500, 30.0),
    ('Системный аналитик', 'Git', 770, 3500, 22.0),
    ('Системный аналитик', 'Docker', 595, 3500, 17.0),
    ('Системный аналитик', 'Microservices', 525, 3500, 15.0),
    ('Системный аналитик', 'gRPC', 420, 3500, 12.0),
    ('Системный аналитик', 'JSON/XML', 350, 3500, 10.0),
    -- Аналитик данных (выборка: 3800 вакансий)
    ('Аналитик данных', 'SQL', 3230, 3800, 85.0),
    ('Аналитик данных', 'Python', 2280, 3800, 60.0),
    ('Аналитик данных', 'Excel', 1900, 3800, 50.0),
    ('Аналитик данных', 'Power BI', 1520, 3800, 40.0),
    ('Аналитик данных', 'Tableau', 912, 3800, 24.0),
    ('Аналитик данных', 'Pandas', 1140, 3800, 30.0),
    ('Аналитик данных', 'Statistics', 836, 3800, 22.0),
    ('Аналитик данных', 'A/B тесты', 684, 3800, 18.0),
    ('Аналитик данных', 'Git', 570, 3800, 15.0),
    ('Аналитик данных', 'Google Analytics', 494, 3800, 13.0),
    ('Аналитик данных', 'Superset/Metabase', 380, 3800, 10.0),
    ('Аналитик данных', 'Airflow', 304, 3800, 8.0),
    -- Продуктовый аналитик (выборка: 2100 вакансий)
    ('Продуктовый аналитик', 'SQL', 1680, 2100, 80.0),
    ('Продуктовый аналитик', 'Python', 1050, 2100, 50.0),
    ('Продуктовый аналитик', 'A/B тесты', 1155, 2100, 55.0),
    ('Продуктовый аналитик', 'Amplitude/Mixpanel', 840, 2100, 40.0),
    ('Продуктовый аналитик', 'Excel', 735, 2100, 35.0),
    ('Продуктовый аналитик', 'Statistics', 630, 2100, 30.0),
    ('Продуктовый аналитик', 'Power BI', 525, 2100, 25.0),
    ('Продуктовый аналитик', 'Google Analytics', 462, 2100, 22.0),
    ('Продуктовый аналитик', 'Tableau', 378, 2100, 18.0),
    ('Продуктовый аналитик', 'Git', 315, 2100, 15.0),
    ('Продуктовый аналитик', 'Pandas', 252, 2100, 12.0),
    ('Продуктовый аналитик', 'JIRA', 210, 2100, 10.0)
ON CONFLICT (profession, skill) DO UPDATE SET
    vacancy_count = EXCLUDED.vacancy_count,
    total_vacancies = EXCLUDED.total_vacancies,
    percentage = EXCLUDED.percentage,
    updated_at = CURRENT_TIMESTAMP;

-- Обновляем тестовые задания: добавляем ещё для новых профессий
INSERT INTO test_assignments (title, description, company, profession, difficulty, skills, source) VALUES
    ('Парсер сайтов на PHP', 'Написать CLI-утилиту для парсинга каталога товаров с пагинацией', 'Ламода', 'PHP разработчик', 'junior', 'PHP,cURL,DOM,JSON', 'demo'),
    ('Микросервис авторизации на Go', 'JWT + refresh tokens, rate limiting, PostgreSQL', 'Озон', 'Golang разработчик', 'middle', 'Go,PostgreSQL,JWT,Docker', 'demo'),
    ('ASP.NET Web API', 'CRUD API с авторизацией и Swagger документацией', 'Kaspersky', 'C# разработчик', 'middle', 'C#,.NET,Entity Framework,SQL', 'demo'),
    ('Автотесты для REST API', 'Фреймворк автотестов с отчётами и CI интеграцией', 'Яндекс', 'AQA / Automation', 'middle', 'Python,pytest,Allure,REST API', 'demo'),
    ('ETL пайплайн', 'Сборка данных из 3 источников в DWH с Airflow', 'СберАналитика', 'Data Scientist', 'senior', 'Python,Apache Spark,SQL,Airflow', 'demo'),
    ('Dashboard для метрик', 'Интерактивный дашборд на Power BI / Superset', 'МТС', 'Аналитик данных', 'junior', 'SQL,Power BI,Python', 'demo'),
    ('Обработка форм 1С', 'Доработка типовой конфигурации УТ 11', 'Softline', '1С программист', 'middle', '1C,SQL,BSP', 'demo'),
    ('iOS приложение погоды', 'SwiftUI + CoreData + OpenWeather API', 'Авито', 'iOS / Swift разработчик', 'junior', 'Swift,SwiftUI,REST API', 'demo'),
    ('Android TODO-app', 'MVVM + Room + Jetpack Compose', 'VK', 'Android разработчик', 'junior', 'Kotlin,Jetpack Compose,Room', 'demo'),
    ('Планировщик задач Flutter', 'Кроссплатформенное приложение с Firebase', 'Сбермаркет', 'Flutter разработчик', 'middle', 'Flutter,Dart,Firebase', 'demo'),
    ('Roadmap продукта', 'Построить roadmap и провести приоритизацию фич', 'Ozon', 'Продукт-менеджер', 'middle', 'RICE,JIRA,Miro,Figma', 'demo'),
    ('Документирование API', 'Описать API Gateway в OpenAPI 3.0 формате', 'Тинькофф', 'Системный аналитик', 'middle', 'OpenAPI,Swagger,REST API,UML', 'demo')
ON CONFLICT DO NOTHING;
